---
- name: create directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - /etc/systemd/system/docker.service.d
    - /etc/docker

- name: create docker.service override
  template:
    src: docker-override.j2
    dest: /etc/systemd/system/docker.service.d/override.conf
  register: docker_service_override
  notify:
    - reload docker unit

- name: create daemon.json
  template:
    src: daemon-json.j2
    dest: /etc/docker/daemon.json
    mode: 0640
  register: docker_daemon_json
  notify:
    - restart docker service

- name: create /var/local/osshelp dir
  file:
    path: "/var/local/osshelp"
    state: directory
    mode: 0700
  when: loki.host is defined and loki.poststart_setup is defined and loki.poststart_setup

- name: create daemon.json for lxd
  template:
    src: daemon-json.j2
    dest: /var/local/osshelp/docker-daemon.json
    mode: 0640
  vars:
    is_var_local_daemon_json: true
  when: loki.host is defined and loki.poststart_setup is defined and loki.poststart_setup

- meta: flush_handlers
