---
- name: install required packages
  apt:
    name: "{{ required_packages }}"
    state: present
    update_cache: true
    cache_valid_time: 86400

- name: add an apt key for docker repo
  apt_key:
    url: "{{ repo_key }}"
    state: present

- name: add a docker repo
  apt_repository:
    repo: "{{ repo_url }}"
    state: present

- name: create user for remap
  user:
    name: "{{ remap_user }}"
    comment: "User for docker userns-remap"
    state: present
    create_home: false
  when: remap_enable

- name: install docker
  apt:
    name: "{{ docker_packages[repo_branch] }}"
    state: present
    update_cache: true
    cache_valid_time: 86400
  when: ansible_distribution_release != 'focal' and
        ansible_distribution_release != 'jammy'

- name: install docker
  apt:
    name: "{{ docker_packages[repo_branch] }}"
    state: present
    update_cache: true
    cache_valid_time: 86400
  when: ansible_distribution_release == 'focal' or
        ansible_distribution_release == 'jammy'
  no_log: true
  register: docker_packages_installation
  ignore_errors: true

# due to stale issue with docker.socket
# on intitial configuration attempt (focal)
# see: https://github.com/docker/for-linux/issues/989
- name: fix installation on focal/jammy
  apt:
    name: "{{ docker_packages[repo_branch] }}"
    state: present
    update_cache: false
  when: "(ansible_distribution_release == 'focal' or
         ansible_distribution_release == 'jammy') and
         docker_packages_installation.rc is defined and
         docker_packages_installation.rc != 0"

- meta: flush_handlers

- name: install docker-compose
  get_url:
    url: "{{ compose_url }}"
    dest: /usr/local/bin/docker-compose
    mode: 0755
  when: install_compose
