---
- name: docker login
  docker_login:
    registry: "{{ item.registry|default('https://index.docker.io/v1/') }}"
    username: "{{ item.user }}"
    password: "{{ item.password }}"
    state: "{{ item.state|default('present') }}"
  loop: "{{ registries }}"
  no_log: true
