---
# TODO
# - docker_network doesn't support ipv6 https://github.com/ansible/ansible/issues/34855

- name: deploy docker network
  docker_network:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ networks }}"
